// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from WorldObjectTemplate.tt />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Eco.Core.Items;
    using Eco.Gameplay.Blocks;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Components.Auth;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Economy;
    using Eco.Gameplay.Housing;
    using Eco.Gameplay.Interactions;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Modules;
    using Eco.Gameplay.Minimap;
    using Eco.Gameplay.Objects;
    using Eco.Gameplay.Occupancy;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Property;
    using Eco.Gameplay.Skills;
    using Eco.Gameplay.Systems;
    using Eco.Gameplay.Systems.TextLinks;
    using Eco.Gameplay.Pipes.LiquidComponents;
    using Eco.Gameplay.Pipes.Gases;
    using Eco.Shared;
    using Eco.Shared.Math;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.Utils;
    using Eco.Shared.View;
    using Eco.Shared.Items;
    using Eco.Shared.Networking;
    using Eco.Gameplay.Pipes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Housing.PropertyValues;
    using Eco.Gameplay.Civics.Objects;
    using Eco.Gameplay.Settlements;
    using Eco.Gameplay.Systems.NewTooltip;
    using Eco.Core.Controller;
    using Eco.Core.Utils;
	using Eco.Gameplay.Components.Storage;
    using static Eco.Gameplay.Housing.PropertyValues.HomeFurnishingValue;
    using static Eco.Gameplay.Components.PartsComponent;
    using Eco.Gameplay.Items.Recipes;


    [Serialized, Category("Hidden")]
    public class ArcFurnaceInitItem : Item
    {
        static ArcFurnaceInitItem()
        {
            WorldObjectOccupancy.InitializePart1();
        }
    }

    //x,y,z   9,6,10

    public static class WorldObjectOccupancy
    {
        public static void InitializePart1()
        {
            WorldObject.AddOccupancy<ArcFurnaceObject>(new List<BlockOccupancy>()
            {
            new BlockOccupancy(new Vector3i(0, 0, 0)),
            new BlockOccupancy(new Vector3i(1, 0, 0)),
            new BlockOccupancy(new Vector3i(2, 0, 0)),
            new BlockOccupancy(new Vector3i(3, 0, 0)),
            new BlockOccupancy(new Vector3i(4, 0, 0)),
            new BlockOccupancy(new Vector3i(5, 0, 0)),
            new BlockOccupancy(new Vector3i(6, 0, 0)),
            new BlockOccupancy(new Vector3i(7, 0, 0)),
            new BlockOccupancy(new Vector3i(8, 0, 0)),
            new BlockOccupancy(new Vector3i(0, 1, 0)),
            new BlockOccupancy(new Vector3i(1, 1, 0)),
            new BlockOccupancy(new Vector3i(2, 1, 0)),
            new BlockOccupancy(new Vector3i(3, 1, 0)),
            new BlockOccupancy(new Vector3i(4, 1, 0)),
            new BlockOccupancy(new Vector3i(5, 1, 0)),
            new BlockOccupancy(new Vector3i(6, 1, 0)),
            new BlockOccupancy(new Vector3i(7, 1, 0)),
            new BlockOccupancy(new Vector3i(8, 1, 0)),
            new BlockOccupancy(new Vector3i(0, 2, 0)),
            new BlockOccupancy(new Vector3i(1, 2, 0)),
            new BlockOccupancy(new Vector3i(2, 2, 0)),
            new BlockOccupancy(new Vector3i(3, 2, 0)),
            new BlockOccupancy(new Vector3i(4, 2, 0)),
            new BlockOccupancy(new Vector3i(5, 2, 0)),
            new BlockOccupancy(new Vector3i(6, 2, 0)),
            new BlockOccupancy(new Vector3i(7, 2, 0)),
            new BlockOccupancy(new Vector3i(8, 2, 0)),
            new BlockOccupancy(new Vector3i(0, 3, 0)),
            new BlockOccupancy(new Vector3i(1, 3, 0)),
            new BlockOccupancy(new Vector3i(2, 3, 0)),
            new BlockOccupancy(new Vector3i(3, 3, 0)),
            new BlockOccupancy(new Vector3i(4, 3, 0)),
            new BlockOccupancy(new Vector3i(5, 3, 0)),
            new BlockOccupancy(new Vector3i(6, 3, 0)),
            new BlockOccupancy(new Vector3i(7, 3, 0)),
            new BlockOccupancy(new Vector3i(8, 3, 0)),
            new BlockOccupancy(new Vector3i(0, 4, 0)),
            new BlockOccupancy(new Vector3i(1, 4, 0)),
            new BlockOccupancy(new Vector3i(2, 4, 0)),
            new BlockOccupancy(new Vector3i(3, 4, 0)),
            new BlockOccupancy(new Vector3i(4, 4, 0)),
            new BlockOccupancy(new Vector3i(5, 4, 0)),
            new BlockOccupancy(new Vector3i(6, 4, 0)),
            new BlockOccupancy(new Vector3i(7, 4, 0)),
            new BlockOccupancy(new Vector3i(8, 4, 0)),
            new BlockOccupancy(new Vector3i(0, 5, 0)),
            new BlockOccupancy(new Vector3i(1, 5, 0)),
            new BlockOccupancy(new Vector3i(2, 5, 0)),
            new BlockOccupancy(new Vector3i(3, 5, 0)),
            new BlockOccupancy(new Vector3i(4, 5, 0)),
            new BlockOccupancy(new Vector3i(5, 5, 0)),
            new BlockOccupancy(new Vector3i(6, 5, 0)),
            new BlockOccupancy(new Vector3i(7, 5, 0)),
            new BlockOccupancy(new Vector3i(8, 5, 0)),
            new BlockOccupancy(new Vector3i(0, 5, 0)),
            new BlockOccupancy(new Vector3i(1, 5, 0)),
            new BlockOccupancy(new Vector3i(2, 5, 0)),
            new BlockOccupancy(new Vector3i(3, 5, 0)),
            new BlockOccupancy(new Vector3i(4, 5, 0)),
            new BlockOccupancy(new Vector3i(5, 5, 0)),
            new BlockOccupancy(new Vector3i(6, 5, 0)),
            new BlockOccupancy(new Vector3i(7, 5, 0)),
            new BlockOccupancy(new Vector3i(8, 5, 0)),
            new BlockOccupancy(new Vector3i(0, 6, 0)),
            new BlockOccupancy(new Vector3i(1, 6, 0)),
            new BlockOccupancy(new Vector3i(2, 6, 0)),
            new BlockOccupancy(new Vector3i(3, 6, 0)),
            new BlockOccupancy(new Vector3i(4, 6, 0)),
            new BlockOccupancy(new Vector3i(5, 6, 0)),
            new BlockOccupancy(new Vector3i(6, 6, 0)),
            new BlockOccupancy(new Vector3i(7, 6, 0)),
            new BlockOccupancy(new Vector3i(8, 6, 0)),
            new BlockOccupancy(new Vector3i(0, 7, 0)),
            new BlockOccupancy(new Vector3i(1, 7, 0)),
            new BlockOccupancy(new Vector3i(2, 7, 0)),
            new BlockOccupancy(new Vector3i(3, 7, 0)),
            new BlockOccupancy(new Vector3i(4, 7, 0)),
            new BlockOccupancy(new Vector3i(5, 7, 0)),
            new BlockOccupancy(new Vector3i(6, 7, 0)),
            new BlockOccupancy(new Vector3i(7, 7, 0)),
            new BlockOccupancy(new Vector3i(8, 7, 0)),
            new BlockOccupancy(new Vector3i(0, 8, 0)),
            new BlockOccupancy(new Vector3i(1, 8, 0)),
            new BlockOccupancy(new Vector3i(2, 8, 0)),
            new BlockOccupancy(new Vector3i(3, 8, 0)),
            new BlockOccupancy(new Vector3i(4, 8, 0)),
            new BlockOccupancy(new Vector3i(5, 8, 0)),
            new BlockOccupancy(new Vector3i(6, 8, 0)),
            new BlockOccupancy(new Vector3i(7, 8, 0)),
            new BlockOccupancy(new Vector3i(8, 8, 0)),
            new BlockOccupancy(new Vector3i(0, 9, 0)),
            new BlockOccupancy(new Vector3i(1, 9, 0)),
            new BlockOccupancy(new Vector3i(2, 9, 0)),
            new BlockOccupancy(new Vector3i(3, 9, 0)),
            new BlockOccupancy(new Vector3i(4, 9, 0)),
            new BlockOccupancy(new Vector3i(5, 9, 0)),
            new BlockOccupancy(new Vector3i(6, 9, 0)),
            new BlockOccupancy(new Vector3i(7, 9, 0)),
            new BlockOccupancy(new Vector3i(8, 9, 0)),
            new BlockOccupancy(new Vector3i(0, 0, 1)),
            new BlockOccupancy(new Vector3i(1, 0, 1)),
            new BlockOccupancy(new Vector3i(2, 0, 1)),
            new BlockOccupancy(new Vector3i(3, 0, 1)),
            new BlockOccupancy(new Vector3i(4, 0, 1)),
            new BlockOccupancy(new Vector3i(5, 0, 1)),
            new BlockOccupancy(new Vector3i(6, 0, 1)),
            new BlockOccupancy(new Vector3i(7, 0, 1)),
            new BlockOccupancy(new Vector3i(8, 0, 1)),
            new BlockOccupancy(new Vector3i(0, 1, 1)),
            new BlockOccupancy(new Vector3i(1, 1, 1)),
            new BlockOccupancy(new Vector3i(2, 1, 1)),
            new BlockOccupancy(new Vector3i(3, 1, 1)),
            new BlockOccupancy(new Vector3i(4, 1, 1)),
            new BlockOccupancy(new Vector3i(5, 1, 1)),
            new BlockOccupancy(new Vector3i(6, 1, 1)),
            new BlockOccupancy(new Vector3i(7, 1, 1)),
            new BlockOccupancy(new Vector3i(8, 1, 1)),
            new BlockOccupancy(new Vector3i(0, 2, 1)),
            new BlockOccupancy(new Vector3i(1, 2, 1)),
            new BlockOccupancy(new Vector3i(2, 2, 1)),
            new BlockOccupancy(new Vector3i(3, 2, 1)),
            new BlockOccupancy(new Vector3i(4, 2, 1)),
            new BlockOccupancy(new Vector3i(5, 2, 1)),
            new BlockOccupancy(new Vector3i(6, 2, 1)),
            new BlockOccupancy(new Vector3i(7, 2, 1)),
            new BlockOccupancy(new Vector3i(8, 2, 1)),
            new BlockOccupancy(new Vector3i(0, 3, 1)),
            new BlockOccupancy(new Vector3i(1, 3, 1)),
            new BlockOccupancy(new Vector3i(2, 3, 1)),
            new BlockOccupancy(new Vector3i(3, 3, 1)),
            new BlockOccupancy(new Vector3i(4, 3, 1)),
            new BlockOccupancy(new Vector3i(5, 3, 1)),
            new BlockOccupancy(new Vector3i(6, 3, 1)),
            new BlockOccupancy(new Vector3i(7, 3, 1)),
            new BlockOccupancy(new Vector3i(8, 3, 1)),
            new BlockOccupancy(new Vector3i(0, 4, 1)),
            new BlockOccupancy(new Vector3i(1, 4, 1)),
            new BlockOccupancy(new Vector3i(2, 4, 1)),
            new BlockOccupancy(new Vector3i(3, 4, 1)),
            new BlockOccupancy(new Vector3i(4, 4, 1)),
            new BlockOccupancy(new Vector3i(5, 4, 1)),
            new BlockOccupancy(new Vector3i(6, 4, 1)),
            new BlockOccupancy(new Vector3i(7, 4, 1)),
            new BlockOccupancy(new Vector3i(8, 4, 1)),
            new BlockOccupancy(new Vector3i(0, 5, 1)),
            new BlockOccupancy(new Vector3i(1, 5, 1)),
            new BlockOccupancy(new Vector3i(2, 5, 1)),
            new BlockOccupancy(new Vector3i(3, 5, 1)),
            new BlockOccupancy(new Vector3i(4, 5, 1)),
            new BlockOccupancy(new Vector3i(5, 5, 1)),
            new BlockOccupancy(new Vector3i(6, 5, 1)),
            new BlockOccupancy(new Vector3i(7, 5, 1)),
            new BlockOccupancy(new Vector3i(8, 5, 1)),
            new BlockOccupancy(new Vector3i(0, 5, 1)),
            new BlockOccupancy(new Vector3i(1, 5, 1)),
            new BlockOccupancy(new Vector3i(2, 5, 1)),
            new BlockOccupancy(new Vector3i(3, 5, 1)),
            new BlockOccupancy(new Vector3i(4, 5, 1)),
            new BlockOccupancy(new Vector3i(5, 5, 1)),
            new BlockOccupancy(new Vector3i(6, 5, 1)),
            new BlockOccupancy(new Vector3i(7, 5, 1)),
            new BlockOccupancy(new Vector3i(8, 5, 1)),
            new BlockOccupancy(new Vector3i(0, 6, 1)),
            new BlockOccupancy(new Vector3i(1, 6, 1)),
            new BlockOccupancy(new Vector3i(2, 6, 1)),
            new BlockOccupancy(new Vector3i(3, 6, 1)),
            new BlockOccupancy(new Vector3i(4, 6, 1)),
            new BlockOccupancy(new Vector3i(5, 6, 1)),
            new BlockOccupancy(new Vector3i(6, 6, 1)),
            new BlockOccupancy(new Vector3i(7, 6, 1)),
            new BlockOccupancy(new Vector3i(8, 6, 1)),
            new BlockOccupancy(new Vector3i(0, 7, 1)),
            new BlockOccupancy(new Vector3i(1, 7, 1)),
            new BlockOccupancy(new Vector3i(2, 7, 1)),
            new BlockOccupancy(new Vector3i(3, 7, 1)),
            new BlockOccupancy(new Vector3i(4, 7, 1)),
            new BlockOccupancy(new Vector3i(5, 7, 1)),
            new BlockOccupancy(new Vector3i(6, 7, 1)),
            new BlockOccupancy(new Vector3i(7, 7, 1)),
            new BlockOccupancy(new Vector3i(8, 7, 1)),
            new BlockOccupancy(new Vector3i(0, 8, 1)),
            new BlockOccupancy(new Vector3i(1, 8, 1)),
            new BlockOccupancy(new Vector3i(2, 8, 1)),
            new BlockOccupancy(new Vector3i(3, 8, 1)),
            new BlockOccupancy(new Vector3i(4, 8, 1)),
            new BlockOccupancy(new Vector3i(5, 8, 1)),
            new BlockOccupancy(new Vector3i(6, 8, 1)),
            new BlockOccupancy(new Vector3i(7, 8, 1)),
            new BlockOccupancy(new Vector3i(8, 8, 1)),
            new BlockOccupancy(new Vector3i(0, 9, 1)),
            new BlockOccupancy(new Vector3i(1, 9, 1)),
            new BlockOccupancy(new Vector3i(2, 9, 1)),
            new BlockOccupancy(new Vector3i(3, 9, 1)),
            new BlockOccupancy(new Vector3i(4, 9, 1)),
            new BlockOccupancy(new Vector3i(5, 9, 1)),
            new BlockOccupancy(new Vector3i(6, 9, 1)),
            new BlockOccupancy(new Vector3i(7, 9, 1)),
            new BlockOccupancy(new Vector3i(8, 9, 1)),
            new BlockOccupancy(new Vector3i(0, 0, 2)),
            new BlockOccupancy(new Vector3i(1, 0, 2)),
            new BlockOccupancy(new Vector3i(2, 0, 2)),
            new BlockOccupancy(new Vector3i(3, 0, 2)),
            new BlockOccupancy(new Vector3i(4, 0, 2)),
            new BlockOccupancy(new Vector3i(5, 0, 2)),
            new BlockOccupancy(new Vector3i(6, 0, 2)),
            new BlockOccupancy(new Vector3i(7, 0, 2)),
            new BlockOccupancy(new Vector3i(8, 0, 2)),
            new BlockOccupancy(new Vector3i(0, 1, 2)),
            new BlockOccupancy(new Vector3i(1, 1, 2)),
            new BlockOccupancy(new Vector3i(2, 1, 2)),
            new BlockOccupancy(new Vector3i(3, 1, 2)),
            new BlockOccupancy(new Vector3i(4, 1, 2)),
            new BlockOccupancy(new Vector3i(5, 1, 2)),
            new BlockOccupancy(new Vector3i(6, 1, 2)),
            new BlockOccupancy(new Vector3i(7, 1, 2)),
            new BlockOccupancy(new Vector3i(8, 1, 2)),
            new BlockOccupancy(new Vector3i(0, 2, 2)),
            new BlockOccupancy(new Vector3i(1, 2, 2)),
            new BlockOccupancy(new Vector3i(2, 2, 2)),
            new BlockOccupancy(new Vector3i(3, 2, 2)),
            new BlockOccupancy(new Vector3i(4, 2, 2)),
            new BlockOccupancy(new Vector3i(5, 2, 2)),
            new BlockOccupancy(new Vector3i(6, 2, 2)),
            new BlockOccupancy(new Vector3i(7, 2, 2)),
            new BlockOccupancy(new Vector3i(8, 2, 2)),
            new BlockOccupancy(new Vector3i(0, 3, 2)),
            new BlockOccupancy(new Vector3i(1, 3, 2)),
            new BlockOccupancy(new Vector3i(2, 3, 2)),
            new BlockOccupancy(new Vector3i(3, 3, 2)),
            new BlockOccupancy(new Vector3i(4, 3, 2)),
            new BlockOccupancy(new Vector3i(5, 3, 2)),
            new BlockOccupancy(new Vector3i(6, 3, 2)),
            new BlockOccupancy(new Vector3i(7, 3, 2)),
            new BlockOccupancy(new Vector3i(8, 3, 2)),
            new BlockOccupancy(new Vector3i(0, 4, 2)),
            new BlockOccupancy(new Vector3i(1, 4, 2)),
            new BlockOccupancy(new Vector3i(2, 4, 2)),
            new BlockOccupancy(new Vector3i(3, 4, 2)),
            new BlockOccupancy(new Vector3i(4, 4, 2)),
            new BlockOccupancy(new Vector3i(5, 4, 2)),
            new BlockOccupancy(new Vector3i(6, 4, 2)),
            new BlockOccupancy(new Vector3i(7, 4, 2)),
            new BlockOccupancy(new Vector3i(8, 4, 2)),
            new BlockOccupancy(new Vector3i(0, 5, 2)),
            new BlockOccupancy(new Vector3i(1, 5, 2)),
            new BlockOccupancy(new Vector3i(2, 5, 2)),
            new BlockOccupancy(new Vector3i(3, 5, 2)),
            new BlockOccupancy(new Vector3i(4, 5, 2)),
            new BlockOccupancy(new Vector3i(5, 5, 2)),
            new BlockOccupancy(new Vector3i(6, 5, 2)),
            new BlockOccupancy(new Vector3i(7, 5, 2)),
            new BlockOccupancy(new Vector3i(8, 5, 2)),
            new BlockOccupancy(new Vector3i(0, 5, 2)),
            new BlockOccupancy(new Vector3i(1, 5, 2)),
            new BlockOccupancy(new Vector3i(2, 5, 2)),
            new BlockOccupancy(new Vector3i(3, 5, 2)),
            new BlockOccupancy(new Vector3i(4, 5, 2)),
            new BlockOccupancy(new Vector3i(5, 5, 2)),
            new BlockOccupancy(new Vector3i(6, 5, 2)),
            new BlockOccupancy(new Vector3i(7, 5, 2)),
            new BlockOccupancy(new Vector3i(8, 5, 2)),
            new BlockOccupancy(new Vector3i(0, 6, 2)),
            new BlockOccupancy(new Vector3i(1, 6, 2)),
            new BlockOccupancy(new Vector3i(2, 6, 2)),
            new BlockOccupancy(new Vector3i(3, 6, 2)),
            new BlockOccupancy(new Vector3i(4, 6, 2)),
            new BlockOccupancy(new Vector3i(5, 6, 2)),
            new BlockOccupancy(new Vector3i(6, 6, 2)),
            new BlockOccupancy(new Vector3i(7, 6, 2)),
            new BlockOccupancy(new Vector3i(8, 6, 2)),
            new BlockOccupancy(new Vector3i(0, 7, 2)),
            new BlockOccupancy(new Vector3i(1, 7, 2)),
            new BlockOccupancy(new Vector3i(2, 7, 2)),
            new BlockOccupancy(new Vector3i(3, 7, 2)),
            new BlockOccupancy(new Vector3i(4, 7, 2)),
            new BlockOccupancy(new Vector3i(5, 7, 2)),
            new BlockOccupancy(new Vector3i(6, 7, 2)),
            new BlockOccupancy(new Vector3i(7, 7, 2)),
            new BlockOccupancy(new Vector3i(8, 7, 2)),
            new BlockOccupancy(new Vector3i(0, 8, 2)),
            new BlockOccupancy(new Vector3i(1, 8, 2)),
            new BlockOccupancy(new Vector3i(2, 8, 2)),
            new BlockOccupancy(new Vector3i(3, 8, 2)),
            new BlockOccupancy(new Vector3i(4, 8, 2)),
            new BlockOccupancy(new Vector3i(5, 8, 2)),
            new BlockOccupancy(new Vector3i(6, 8, 2)),
            new BlockOccupancy(new Vector3i(7, 8, 2)),
            new BlockOccupancy(new Vector3i(8, 8, 2)),
            new BlockOccupancy(new Vector3i(0, 9, 2)),
            new BlockOccupancy(new Vector3i(1, 9, 2)),
            new BlockOccupancy(new Vector3i(2, 9, 2)),
            new BlockOccupancy(new Vector3i(3, 9, 2)),
            new BlockOccupancy(new Vector3i(4, 9, 2)),
            new BlockOccupancy(new Vector3i(5, 9, 2)),
            new BlockOccupancy(new Vector3i(6, 9, 2)),
            new BlockOccupancy(new Vector3i(7, 9, 2)),
            new BlockOccupancy(new Vector3i(8, 9, 2)),
            new BlockOccupancy(new Vector3i(0, 0, 3)),
            new BlockOccupancy(new Vector3i(1, 0, 3)),
            new BlockOccupancy(new Vector3i(2, 0, 3)),
            new BlockOccupancy(new Vector3i(3, 0, 3)),
            new BlockOccupancy(new Vector3i(4, 0, 3)),
            new BlockOccupancy(new Vector3i(5, 0, 3)),
            new BlockOccupancy(new Vector3i(6, 0, 3)),
            new BlockOccupancy(new Vector3i(7, 0, 3)),
            new BlockOccupancy(new Vector3i(8, 0, 3)),
            new BlockOccupancy(new Vector3i(0, 1, 3)),
            new BlockOccupancy(new Vector3i(1, 1, 3)),
            new BlockOccupancy(new Vector3i(2, 1, 3)),
            new BlockOccupancy(new Vector3i(3, 1, 3)),
            new BlockOccupancy(new Vector3i(4, 1, 3)),
            new BlockOccupancy(new Vector3i(5, 1, 3)),
            new BlockOccupancy(new Vector3i(6, 1, 3)),
            new BlockOccupancy(new Vector3i(7, 1, 3)),
            new BlockOccupancy(new Vector3i(8, 1, 3)),
            new BlockOccupancy(new Vector3i(0, 2, 3)),
            new BlockOccupancy(new Vector3i(1, 2, 3)),
            new BlockOccupancy(new Vector3i(2, 2, 3)),
            new BlockOccupancy(new Vector3i(3, 2, 3)),
            new BlockOccupancy(new Vector3i(4, 2, 3)),
            new BlockOccupancy(new Vector3i(5, 2, 3)),
            new BlockOccupancy(new Vector3i(6, 2, 3)),
            new BlockOccupancy(new Vector3i(7, 2, 3)),
            new BlockOccupancy(new Vector3i(8, 2, 3)),
            new BlockOccupancy(new Vector3i(0, 3, 3)),
            new BlockOccupancy(new Vector3i(1, 3, 3)),
            new BlockOccupancy(new Vector3i(2, 3, 3)),
            new BlockOccupancy(new Vector3i(3, 3, 3)),
            new BlockOccupancy(new Vector3i(4, 3, 3)),
            new BlockOccupancy(new Vector3i(5, 3, 3)),
            new BlockOccupancy(new Vector3i(6, 3, 3)),
            new BlockOccupancy(new Vector3i(7, 3, 3)),
            new BlockOccupancy(new Vector3i(8, 3, 3)),
            new BlockOccupancy(new Vector3i(0, 4, 3)),
            new BlockOccupancy(new Vector3i(1, 4, 3)),
            new BlockOccupancy(new Vector3i(2, 4, 3)),
            new BlockOccupancy(new Vector3i(3, 4, 3)),
            new BlockOccupancy(new Vector3i(4, 4, 3)),
            new BlockOccupancy(new Vector3i(5, 4, 3)),
            new BlockOccupancy(new Vector3i(6, 4, 3)),
            new BlockOccupancy(new Vector3i(7, 4, 3)),
            new BlockOccupancy(new Vector3i(8, 4, 3)),
            new BlockOccupancy(new Vector3i(0, 5, 3)),
            new BlockOccupancy(new Vector3i(1, 5, 3)),
            new BlockOccupancy(new Vector3i(2, 5, 3)),
            new BlockOccupancy(new Vector3i(3, 5, 3)),
            new BlockOccupancy(new Vector3i(4, 5, 3)),
            new BlockOccupancy(new Vector3i(5, 5, 3)),
            new BlockOccupancy(new Vector3i(6, 5, 3)),
            new BlockOccupancy(new Vector3i(7, 5, 3)),
            new BlockOccupancy(new Vector3i(8, 5, 3)),
            new BlockOccupancy(new Vector3i(0, 5, 3)),
            new BlockOccupancy(new Vector3i(1, 5, 3)),
            new BlockOccupancy(new Vector3i(2, 5, 3)),
            new BlockOccupancy(new Vector3i(3, 5, 3)),
            new BlockOccupancy(new Vector3i(4, 5, 3)),
            new BlockOccupancy(new Vector3i(5, 5, 3)),
            new BlockOccupancy(new Vector3i(6, 5, 3)),
            new BlockOccupancy(new Vector3i(7, 5, 3)),
            new BlockOccupancy(new Vector3i(8, 5, 3)),
            new BlockOccupancy(new Vector3i(0, 6, 3)),
            new BlockOccupancy(new Vector3i(1, 6, 3)),
            new BlockOccupancy(new Vector3i(2, 6, 3)),
            new BlockOccupancy(new Vector3i(3, 6, 3)),
            new BlockOccupancy(new Vector3i(4, 6, 3)),
            new BlockOccupancy(new Vector3i(5, 6, 3)),
            new BlockOccupancy(new Vector3i(6, 6, 3)),
            new BlockOccupancy(new Vector3i(7, 6, 3)),
            new BlockOccupancy(new Vector3i(8, 6, 3)),
            new BlockOccupancy(new Vector3i(0, 7, 3)),
            new BlockOccupancy(new Vector3i(1, 7, 3)),
            new BlockOccupancy(new Vector3i(2, 7, 3)),
            new BlockOccupancy(new Vector3i(3, 7, 3)),
            new BlockOccupancy(new Vector3i(4, 7, 3)),
            new BlockOccupancy(new Vector3i(5, 7, 3)),
            new BlockOccupancy(new Vector3i(6, 7, 3)),
            new BlockOccupancy(new Vector3i(7, 7, 3)),
            new BlockOccupancy(new Vector3i(8, 7, 3)),
            new BlockOccupancy(new Vector3i(0, 8, 3)),
            new BlockOccupancy(new Vector3i(1, 8, 3)),
            new BlockOccupancy(new Vector3i(2, 8, 3)),
            new BlockOccupancy(new Vector3i(3, 8, 3)),
            new BlockOccupancy(new Vector3i(4, 8, 3)),
            new BlockOccupancy(new Vector3i(5, 8, 3)),
            new BlockOccupancy(new Vector3i(6, 8, 3)),
            new BlockOccupancy(new Vector3i(7, 8, 3)),
            new BlockOccupancy(new Vector3i(8, 8, 3)),
            new BlockOccupancy(new Vector3i(0, 9, 3)),
            new BlockOccupancy(new Vector3i(1, 9, 3)),
            new BlockOccupancy(new Vector3i(2, 9, 3)),
            new BlockOccupancy(new Vector3i(3, 9, 3)),
            new BlockOccupancy(new Vector3i(4, 9, 3)),
            new BlockOccupancy(new Vector3i(5, 9, 3)),
            new BlockOccupancy(new Vector3i(6, 9, 3)),
            new BlockOccupancy(new Vector3i(7, 9, 3)),
            new BlockOccupancy(new Vector3i(8, 9, 3)),
            new BlockOccupancy(new Vector3i(0, 0, 4)),
            new BlockOccupancy(new Vector3i(1, 0, 4)),
            new BlockOccupancy(new Vector3i(2, 0, 4)),
            new BlockOccupancy(new Vector3i(3, 0, 4)),
            new BlockOccupancy(new Vector3i(4, 0, 4)),
            new BlockOccupancy(new Vector3i(5, 0, 4)),
            new BlockOccupancy(new Vector3i(6, 0, 4)),
            new BlockOccupancy(new Vector3i(7, 0, 4)),
            new BlockOccupancy(new Vector3i(8, 0, 4)),
            new BlockOccupancy(new Vector3i(0, 1, 4)),
            new BlockOccupancy(new Vector3i(1, 1, 4)),
            new BlockOccupancy(new Vector3i(2, 1, 4)),
            new BlockOccupancy(new Vector3i(3, 1, 4)),
            new BlockOccupancy(new Vector3i(4, 1, 4)),
            new BlockOccupancy(new Vector3i(5, 1, 4)),
            new BlockOccupancy(new Vector3i(6, 1, 4)),
            new BlockOccupancy(new Vector3i(7, 1, 4)),
            new BlockOccupancy(new Vector3i(8, 1, 4)),
            new BlockOccupancy(new Vector3i(0, 2, 4)),
            new BlockOccupancy(new Vector3i(1, 2, 4)),
            new BlockOccupancy(new Vector3i(2, 2, 4)),
            new BlockOccupancy(new Vector3i(3, 2, 4)),
            new BlockOccupancy(new Vector3i(4, 2, 4)),
            new BlockOccupancy(new Vector3i(5, 2, 4)),
            new BlockOccupancy(new Vector3i(6, 2, 4)),
            new BlockOccupancy(new Vector3i(7, 2, 4)),
            new BlockOccupancy(new Vector3i(8, 2, 4)),
            new BlockOccupancy(new Vector3i(0, 3, 4)),
            new BlockOccupancy(new Vector3i(1, 3, 4)),
            new BlockOccupancy(new Vector3i(2, 3, 4)),
            new BlockOccupancy(new Vector3i(3, 3, 4)),
            new BlockOccupancy(new Vector3i(4, 3, 4)),
            new BlockOccupancy(new Vector3i(5, 3, 4)),
            new BlockOccupancy(new Vector3i(6, 3, 4)),
            new BlockOccupancy(new Vector3i(7, 3, 4)),
            new BlockOccupancy(new Vector3i(8, 3, 4)),
            new BlockOccupancy(new Vector3i(0, 4, 4)),
            new BlockOccupancy(new Vector3i(1, 4, 4)),
            new BlockOccupancy(new Vector3i(2, 4, 4)),
            new BlockOccupancy(new Vector3i(3, 4, 4)),
            new BlockOccupancy(new Vector3i(4, 4, 4)),
            new BlockOccupancy(new Vector3i(5, 4, 4)),
            new BlockOccupancy(new Vector3i(6, 4, 4)),
            new BlockOccupancy(new Vector3i(7, 4, 4)),
            new BlockOccupancy(new Vector3i(8, 4, 4)),
            new BlockOccupancy(new Vector3i(0, 5, 4)),
            new BlockOccupancy(new Vector3i(1, 5, 4)),
            new BlockOccupancy(new Vector3i(2, 5, 4)),
            new BlockOccupancy(new Vector3i(3, 5, 4)),
            new BlockOccupancy(new Vector3i(4, 5, 4)),
            new BlockOccupancy(new Vector3i(5, 5, 4)),
            new BlockOccupancy(new Vector3i(6, 5, 4)),
            new BlockOccupancy(new Vector3i(7, 5, 4)),
            new BlockOccupancy(new Vector3i(8, 5, 4)),
            new BlockOccupancy(new Vector3i(0, 5, 4)),
            new BlockOccupancy(new Vector3i(1, 5, 4)),
            new BlockOccupancy(new Vector3i(2, 5, 4)),
            new BlockOccupancy(new Vector3i(3, 5, 4)),
            new BlockOccupancy(new Vector3i(4, 5, 4)),
            new BlockOccupancy(new Vector3i(5, 5, 4)),
            new BlockOccupancy(new Vector3i(6, 5, 4)),
            new BlockOccupancy(new Vector3i(7, 5, 4)),
            new BlockOccupancy(new Vector3i(8, 5, 4)),
            new BlockOccupancy(new Vector3i(0, 6, 4)),
            new BlockOccupancy(new Vector3i(1, 6, 4)),
            new BlockOccupancy(new Vector3i(2, 6, 4)),
            new BlockOccupancy(new Vector3i(3, 6, 4)),
            new BlockOccupancy(new Vector3i(4, 6, 4)),
            new BlockOccupancy(new Vector3i(5, 6, 4)),
            new BlockOccupancy(new Vector3i(6, 6, 4)),
            new BlockOccupancy(new Vector3i(7, 6, 4)),
            new BlockOccupancy(new Vector3i(8, 6, 4)),
            new BlockOccupancy(new Vector3i(0, 7, 4)),
            new BlockOccupancy(new Vector3i(1, 7, 4)),
            new BlockOccupancy(new Vector3i(2, 7, 4)),
            new BlockOccupancy(new Vector3i(3, 7, 4)),
            new BlockOccupancy(new Vector3i(4, 7, 4)),
            new BlockOccupancy(new Vector3i(5, 7, 4)),
            new BlockOccupancy(new Vector3i(6, 7, 4)),
            new BlockOccupancy(new Vector3i(7, 7, 4)),
            new BlockOccupancy(new Vector3i(8, 7, 4)),
            new BlockOccupancy(new Vector3i(0, 8, 4)),
            new BlockOccupancy(new Vector3i(1, 8, 4)),
            new BlockOccupancy(new Vector3i(2, 8, 4)),
            new BlockOccupancy(new Vector3i(3, 8, 4)),
            new BlockOccupancy(new Vector3i(4, 8, 4)),
            new BlockOccupancy(new Vector3i(5, 8, 4)),
            new BlockOccupancy(new Vector3i(6, 8, 4)),
            new BlockOccupancy(new Vector3i(7, 8, 4)),
            new BlockOccupancy(new Vector3i(8, 8, 4)),
            new BlockOccupancy(new Vector3i(0, 9, 4)),
            new BlockOccupancy(new Vector3i(1, 9, 4)),
            new BlockOccupancy(new Vector3i(2, 9, 4)),
            new BlockOccupancy(new Vector3i(3, 9, 4)),
            new BlockOccupancy(new Vector3i(4, 9, 4)),
            new BlockOccupancy(new Vector3i(5, 9, 4)),
            new BlockOccupancy(new Vector3i(6, 9, 4)),
            new BlockOccupancy(new Vector3i(7, 9, 4)),
            new BlockOccupancy(new Vector3i(8, 9, 4)),
            new BlockOccupancy(new Vector3i(0, 0, 1)),
            new BlockOccupancy(new Vector3i(1, 0, 1)),
            new BlockOccupancy(new Vector3i(2, 0, 5)),
            new BlockOccupancy(new Vector3i(3, 0, 5)),
            new BlockOccupancy(new Vector3i(4, 0, 5)),
            new BlockOccupancy(new Vector3i(5, 0, 5)),
            new BlockOccupancy(new Vector3i(6, 0, 5)),
            new BlockOccupancy(new Vector3i(7, 0, 5)),
            new BlockOccupancy(new Vector3i(8, 0, 5)),
            new BlockOccupancy(new Vector3i(0, 1, 5)),
            new BlockOccupancy(new Vector3i(1, 1, 5)),
            new BlockOccupancy(new Vector3i(2, 1, 5)),
            new BlockOccupancy(new Vector3i(3, 1, 5)),
            new BlockOccupancy(new Vector3i(4, 1, 5)),
            new BlockOccupancy(new Vector3i(5, 1, 5)),
            new BlockOccupancy(new Vector3i(6, 1, 5)),
            new BlockOccupancy(new Vector3i(7, 1, 5)),
            new BlockOccupancy(new Vector3i(8, 1, 5)),
            new BlockOccupancy(new Vector3i(0, 2, 5)),
            new BlockOccupancy(new Vector3i(1, 2, 5)),
            new BlockOccupancy(new Vector3i(2, 2, 5)),
            new BlockOccupancy(new Vector3i(3, 2, 5)),
            new BlockOccupancy(new Vector3i(4, 2, 5)),
            new BlockOccupancy(new Vector3i(5, 2, 5)),
            new BlockOccupancy(new Vector3i(6, 2, 5)),
            new BlockOccupancy(new Vector3i(7, 2, 5)),
            new BlockOccupancy(new Vector3i(8, 2, 5)),
            new BlockOccupancy(new Vector3i(0, 3, 5)),
            new BlockOccupancy(new Vector3i(1, 3, 5)),
            new BlockOccupancy(new Vector3i(2, 3, 5)),
            new BlockOccupancy(new Vector3i(3, 3, 5)),
            new BlockOccupancy(new Vector3i(4, 3, 5)),
            new BlockOccupancy(new Vector3i(5, 3, 5)),
            new BlockOccupancy(new Vector3i(6, 3, 5)),
            new BlockOccupancy(new Vector3i(7, 3, 5)),
            new BlockOccupancy(new Vector3i(8, 3, 5)),
            new BlockOccupancy(new Vector3i(0, 4, 5)),
            new BlockOccupancy(new Vector3i(1, 4, 5)),
            new BlockOccupancy(new Vector3i(2, 4, 5)),
            new BlockOccupancy(new Vector3i(3, 4, 5)),
            new BlockOccupancy(new Vector3i(4, 4, 5)),
            new BlockOccupancy(new Vector3i(5, 4, 5)),
            new BlockOccupancy(new Vector3i(6, 4, 5)),
            new BlockOccupancy(new Vector3i(7, 4, 5)),
            new BlockOccupancy(new Vector3i(8, 4, 5)),
            new BlockOccupancy(new Vector3i(0, 5, 5)),
            new BlockOccupancy(new Vector3i(1, 5, 5)),
            new BlockOccupancy(new Vector3i(2, 5, 5)),
            new BlockOccupancy(new Vector3i(3, 5, 5)),
            new BlockOccupancy(new Vector3i(4, 5, 5)),
            new BlockOccupancy(new Vector3i(5, 5, 5)),
            new BlockOccupancy(new Vector3i(6, 5, 5)),
            new BlockOccupancy(new Vector3i(7, 5, 5)),
            new BlockOccupancy(new Vector3i(8, 5, 5)),
            new BlockOccupancy(new Vector3i(0, 5, 5)),
            new BlockOccupancy(new Vector3i(1, 5, 5)),
            new BlockOccupancy(new Vector3i(2, 5, 5)),
            new BlockOccupancy(new Vector3i(3, 5, 5)),
            new BlockOccupancy(new Vector3i(4, 5, 5)),
            new BlockOccupancy(new Vector3i(5, 5, 5)),
            new BlockOccupancy(new Vector3i(6, 5, 5)),
            new BlockOccupancy(new Vector3i(7, 5, 5)),
            new BlockOccupancy(new Vector3i(8, 5, 5)),
            new BlockOccupancy(new Vector3i(0, 6, 5)),
            new BlockOccupancy(new Vector3i(1, 6, 5)),
            new BlockOccupancy(new Vector3i(2, 6, 5)),
            new BlockOccupancy(new Vector3i(3, 6, 5)),
            new BlockOccupancy(new Vector3i(4, 6, 5)),
            new BlockOccupancy(new Vector3i(5, 6, 5)),
            new BlockOccupancy(new Vector3i(6, 6, 5)),
            new BlockOccupancy(new Vector3i(7, 6, 5)),
            new BlockOccupancy(new Vector3i(8, 6, 5)),
            new BlockOccupancy(new Vector3i(0, 7, 5)),
            new BlockOccupancy(new Vector3i(1, 7, 5)),
            new BlockOccupancy(new Vector3i(2, 7, 5)),
            new BlockOccupancy(new Vector3i(3, 7, 5)),
            new BlockOccupancy(new Vector3i(4, 7, 5)),
            new BlockOccupancy(new Vector3i(5, 7, 5)),
            new BlockOccupancy(new Vector3i(6, 7, 5)),
            new BlockOccupancy(new Vector3i(7, 7, 5)),
            new BlockOccupancy(new Vector3i(8, 7, 5)),
            new BlockOccupancy(new Vector3i(0, 8, 5)),
            new BlockOccupancy(new Vector3i(1, 8, 5)),
            new BlockOccupancy(new Vector3i(2, 8, 5)),
            new BlockOccupancy(new Vector3i(3, 8, 5)),
            new BlockOccupancy(new Vector3i(4, 8, 5)),
            new BlockOccupancy(new Vector3i(5, 8, 5)),
            new BlockOccupancy(new Vector3i(6, 8, 5)),
            new BlockOccupancy(new Vector3i(7, 8, 5)),
            new BlockOccupancy(new Vector3i(8, 8, 5)),
            new BlockOccupancy(new Vector3i(0, 9, 5)),
            new BlockOccupancy(new Vector3i(1, 9, 5)),
            new BlockOccupancy(new Vector3i(2, 9, 5)),
            new BlockOccupancy(new Vector3i(3, 9, 5)),
            new BlockOccupancy(new Vector3i(4, 9, 5)),
            new BlockOccupancy(new Vector3i(5, 9, 5)),
            new BlockOccupancy(new Vector3i(6, 9, 5)),
            new BlockOccupancy(new Vector3i(7, 9, 5)),
            new BlockOccupancy(new Vector3i(8, 9, 5)),


            });
        }
    }

    [Serialized]
    //[RequireComponent(typeof(AirPollutionComponent))]
    //[RequireComponent(typeof(ChimneyComponent))]
    //[RequireComponent(typeof(LiquidProducerComponent))]
    [RequireComponent(typeof(AttachmentComponent))]
    [RequireComponent(typeof(OnOffComponent))]
    [RequireComponent(typeof(PropertyAuthComponent))]
    [RequireComponent(typeof(MinimapComponent))]
    [RequireComponent(typeof(LinkComponent))]
    [RequireComponent(typeof(CraftingComponent))]
    [RequireComponent(typeof(PartsComponent))]
    [RequireComponent(typeof(PowerGridComponent))]
    [RequireComponent(typeof(PowerConsumptionComponent))]
    [RequireComponent(typeof(HousingComponent))]
    [RequireComponent(typeof(OccupancyRequirementComponent))]
    //[RequireComponent(typeof(LiquidConverterComponent))]
    [RequireComponent(typeof(PluginModulesComponent))]
    [RequireComponent(typeof(ForSaleComponent))]
    [RequireComponent(typeof(RoomRequirementsComponent))]
    //[RequireRoomContainment]
    //[RequireRoomVolume(100)]
    //[RequireRoomMaterialTier(3.5f, typeof(MetallurgyLavishReqTalent), typeof(MetallurgyFrugalReqTalent))]
    [Tag("Usable")]
    [Ecopedia("Work Stations", "Craft Tables", subPageName: "Arc Furnace Item")]
    [RepairRequiresSkill(typeof(MechanicsSkill), 1)]
            [RepairRequiresSkill(typeof(SelfImprovementSkill), 5)]

   

    public partial class ArcFurnaceObject : WorldObject, IRepresentsItem
    {
        public virtual Type RepresentedItemType => typeof(ArcFurnaceItem);
        public override LocString DisplayName => Localizer.DoStr("Arc Furnace");
        public override TableTextureMode TableTexture => TableTextureMode.Metal;

        protected override void Initialize()
        {
            this.ModsPreInitialize();
            this.GetComponent<MinimapComponent>().SetCategory(Localizer.DoStr("Crafting"));
            this.GetComponent<PowerConsumptionComponent>().Initialize(1500);
            this.GetComponent<PowerGridComponent>().Initialize(10, new ElectricPower());
            this.GetComponent<HousingComponent>().HomeValue = ArcFurnaceItem.homeValue;
            //this.GetComponent<LiquidProducerComponent>().Setup(typeof(SmogItem), 1, BlockOccupancyType.ChimneyOut);
            //this.GetComponent<AirPollutionComponent>().Initialize(this.GetComponent<LiquidProducerComponent>());
            //this.GetComponent<LiquidConverterComponent>().Setup(typeof(WaterItem), typeof(SewageItem), BlockOccupancyType.WaterInputPort, BlockOccupancyType.SewageOutputPort, 0.6f, 0.9f);
            this.ModsPostInitialize();
            {
                this.GetComponent<PartsComponent>().Config(() => LocString.Empty, new PartInfo[]
                {
                                        new() { TypeName = nameof(HeatingElementItem), Quantity = 1},
                                    });
            }
        }

        /// <summary>Hook for mods to customize WorldObject before initialization. You can change housing values here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize WorldObject after initialization.</summary>
        partial void ModsPostInitialize();
    }

    [Serialized]
    [LocDisplayName("Arc Furnace")]
    [LocDescription("An electric arc furnace that produces high volumes of ore at a better rate.")]
    [IconGroup("World Object Minimap")]
    [Ecopedia("Work Stations", "Craft Tables", createAsSubPage: true)]
    [LiquidProducer(typeof(SmogItem), 1)]
    [Weight(10000)] // Defines how heavy BlastFurnace is.
    [Tag(nameof(SurfaceTags.CanBeOnRug))] 
        [AllowPluginModules(Tags = new[] { "AdvancedUpgrade" }, ItemTypes = new[] { typeof(AdvancedSmeltingUpgradeItem), typeof(SmeltingUpgradeItem), typeof(MasonryAdvancedUpgradeItem) })] //noloc
    public partial class ArcFurnaceItem : WorldObjectItem<ArcFurnaceObject>, IPersistentData
    {
        protected override OccupancyContext GetOccupancyContext => new SideAttachedContext( 0  | DirectionAxisFlags.Down , WorldObject.GetOccupancyInfo(this.WorldObjectType));
        public override HomeFurnishingValue HomeValue => homeValue;
        public static readonly HomeFurnishingValue homeValue = new HomeFurnishingValue()
        {
            ObjectName                              = typeof(ArcFurnaceObject).UILink(),
            Category                                = HousingConfig.GetRoomCategory("Industrial"),
            TypeForRoomLimit                        = Localizer.DoStr(""),
            
        };

        [NewTooltip(CacheAs.SubType, 7)] public static LocString PowerConsumptionTooltip() => Localizer.Do($"Consumes: {Text.Info(1500)}w of {new ElectricPower().Name} power.");
        [Serialized, SyncToView, NewTooltipChildren(CacheAs.Instance, flags: TTFlags.AllowNonControllerTypeForChildren)] public object PersistentData { get; set; }
    }

    /// <summary>
    /// <para>Server side recipe definition for "BlastFurnace".</para>
    /// <para>More information about RecipeFamily objects can be found at https://docs.play.eco/api/server/eco.gameplay/Eco.Gameplay.Items.RecipeFamily.html</para>
    /// </summary>
    /// <remarks>
    /// This is an auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization. 
    /// If you wish to modify this class, please create a new partial class or follow the instructions in the "UserCode" folder to override the entire file.
    /// </remarks>
    [RequiresSkill(typeof(MechanicsSkill), 7)]
    [Ecopedia("Work Stations", "Craft Tables", subPageName: "Arc Furnace Item")]
    public partial class ArcFurnaceRecipe : RecipeFamily
    {
        public ArcFurnaceRecipe()
        {
            var recipe = new Recipe();
            recipe.Init(
                name: "ArcFurnace",  //noloc
                displayName: Localizer.DoStr("Arc Furnace"),

                // Defines the ingredients needed to craft this recipe. An ingredient items takes the following inputs
                // type of the item, the amount of the item, the skill required, and the talent used.
                ingredients: new List<IngredientElement>
                {
                    new IngredientElement(typeof(ScrewsItem), 12, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                    new IngredientElement(typeof(ReinforcedConcreteItem), 8, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                    new IngredientElement(typeof(SteelPlateItem), 12, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                    new IngredientElement(typeof(SteelPipeItem), 8, typeof(MechanicsSkill), typeof(MechanicsLavishResourcesTalent)),
                    new IngredientElement(typeof(HeatingElementItem), 2, true),

                },

                // Define our recipe output items.
                // For every output item there needs to be one CraftingElement entry with the type of the final item and the amount
                // to create.
                items: new List<CraftingElement>
                {
                    new CraftingElement<ArcFurnaceItem>()
                });
            this.Recipes = new List<Recipe> { recipe };
            this.ExperienceOnCraft = 20; // Defines how much experience is gained when crafted.
            
            // Defines the amount of labor required and the required skill to add labor
            this.LaborInCalories = CreateLaborInCaloriesValue(2000, typeof(MechanicsSkill));

            // Defines our crafting time for the recipe
            this.CraftMinutes = CreateCraftTimeValue(beneficiary: typeof(ArcFurnaceRecipe), start: 45, skillType: typeof(MechanicsSkill), typeof(MechanicsFocusedSpeedTalent), typeof(MechanicsParallelSpeedTalent));

            // Perform pre/post initialization for user mods and initialize our recipe instance with the display name "Blast Furnace"
            this.ModsPreInitialize();
            this.Initialize(displayText: Localizer.DoStr("Arc Furnace"), recipeType: typeof(ArcFurnaceRecipe));
            this.ModsPostInitialize();

            // Register our RecipeFamily instance with the crafting system so it can be crafted.
            CraftingComponent.AddRecipe(tableType: typeof(AssemblyLineObject), recipe: this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();

        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
